import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export const generatePrescriptionPDF = (prescription, patient, doctor) => {
    return new Promise((resolve, reject) => {
        try {
            const outputDir = path.join("public", "temp");
            if (!fs.existsSync(outputDir)) {
                fs.mkdirSync(outputDir, { recursive: true });
            }

            const fileName = `prescription-${prescription._id}.pdf`;
            const filePath = path.join(outputDir, fileName);

            const doc = new PDFDocument({ margin: 40, size: "A4" });
            const stream = fs.createWriteStream(filePath);

            stream.on("finish", () => {
                resolve(filePath); // return ONLY when file is 100% ready
            });

            stream.on("error", (err) => {
                reject(err);
            });

            doc.pipe(stream);

            // ===== PDF CONTENT =====
            doc.fontSize(20).text("Prescription", { align: "center" }).moveDown(1);

            doc.fontSize(14).text("Doctor Details", { underline: true });
            doc.fontSize(12)
                .text(`Name: ${doctor.name}`)
                .text(`Email: ${doctor.email}`)
                .text(`Phone: ${doctor.phoneNumber}`)
                .moveDown(1);

            doc.fontSize(14).text("Patient Details", { underline: true });
            doc.fontSize(12)
                .text(`Name: ${patient.name}`)
                .text(`Email: ${patient.email}`)
                .text(`Phone: ${patient.phoneNumber}`)
                .moveDown(1);

            doc.fontSize(14).text("Care To Be Taken", { underline: true });
            doc.fontSize(12).text(prescription.careToBeTaken, { width: 500 }).moveDown(1);

            doc.fontSize(14).text("Medicines", { underline: true });
            doc.fontSize(12);

            const meds = prescription.medicines
                .split(",")
                .map(m => m.trim());

            meds.forEach(m => doc.text(`• ${m}`));

            doc.moveDown(2);
            doc.fontSize(10).text("Generated by Online Prescription System", { align: "center" });

            doc.end(); // MUST be last
        } catch (error) {
            reject(error);
        }
    });
};
