import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

export const generatePrescriptionPDF = async (prescription, patient, doctor) => {
    return new Promise((resolve, reject) => {
        try {
            // Ensure folder exists
            const outputDir = path.join("public", "temp");
            if (!fs.existsSync(outputDir)) {
                fs.mkdirSync(outputDir, { recursive: true });
            }

            const fileName = `prescription-${prescription._id}.pdf`;
            const filePath = path.join(outputDir, fileName);

            const doc = new PDFDocument({
                margin: 40,
                size: "A4"
            });

            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // ---------- HEADER ----------
            doc.fontSize(20).text("Prescription", { align: "center" });
            doc.moveDown(1);

            // ---------- DOCTOR INFO ----------
            doc.fontSize(14).text("Doctor Details", { underline: true });
            doc.moveDown(0.5);
            doc.fontSize(12);
            doc.text(`Name: ${doctor.name}`);
            doc.text(`Email: ${doctor.email}`);
            doc.text(`Phone: ${doctor.phoneNumber}`);
            doc.moveDown(1);

            // ---------- PATIENT INFO ----------
            doc.fontSize(14).text("Patient Details", { underline: true });
            doc.moveDown(0.5);
            doc.fontSize(12);
            doc.text(`Name: ${patient.name}`);
            doc.text(`Email: ${patient.email}`);
            doc.text(`Phone: ${patient.phoneNumber}`);
            doc.moveDown(1);

            // ---------- CARE TO BE TAKEN ----------
            doc.fontSize(14).text("Care To Be Taken", { underline: true });
            doc.moveDown(0.5);
            doc.fontSize(12).text(prescription.careToBeTaken, {
                width: 500
            });
            doc.moveDown(1);

            // ---------- MEDICINES ----------
            doc.fontSize(14).text("Medicines", { underline: true });
            doc.moveDown(0.5);
            doc.fontSize(12);

            const medicinesList = Array.isArray(prescription.medicines)
                ? prescription.medicines
                : prescription.medicines.split(",").map(m => m.trim());

            medicinesList.forEach((item, index) => {
                doc.text(`• ${item}`);
            });

            // ---------- FOOTER ----------
            doc.moveDown(2);
            doc.fontSize(10).text("Generated by Online Prescription System", {
                align: "center"
            });

            doc.end();

            stream.on("finish", () => {
                resolve(filePath);
            });

            stream.on("error", (err) => {
                reject(err);
            });
        } catch (error) {
            reject(error);
        }
    });
};
